// app/layout.tsx
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Footer from './components/footer';
import Header from './components/header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: '展翼航空 Stelwing',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-Hant">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--background)] text-[var(--foreground)]`}
      >
        <div className="flex min-h-screen flex-col">
          {/* 固定在頂端的導覽列 */}
          <Header className="fixed left-0 top-0 z-50 w-full" />

          {/* 讓出 header 的高度：依你的 header 高度微調 (例 72px 或 80px) */}
          <main className="flex-1 pt-[80px]">{children}</main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
